import { createApp } from 'vue';
import './assets/main.css';
import App from './App.vue';
import { VueQueryPlugin } from '@tanstack/vue-query';
import { createPinia } from 'pinia';
import router from './router/index.ts';
const app = createApp(App);
app.use(VueQueryPlugin);
app.use(createPinia());
app.use(router);
app.mount('#app');
